# Generated by Django 4.2.23 on 2025-08-22 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='published_date',
        ),
    ]
