# Generated by Django 4.2.23 on 2025-07-30 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mymodel',
            options={'permissions': [('can_create', 'Can add book'), ('can_edit', 'Can edit book'), ('can_delete', 'Can delete book'), ('can_view', 'Can view book')]},
        ),
    ]
